"""add uuids to comments, posts, and users

Revision ID: 774a71079814
Revises: a88bdfa8b66b
Create Date: 2022-02-20 15:10:35.012893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
# revision identifiers, used by Alembic.
revision = '774a71079814'
down_revision = 'a88bdfa8b66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'comments', ['uuid'])
    op.add_column('posts', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'posts', ['uuid'])
    op.add_column('users', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'uuid')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'uuid')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_column('comments', 'uuid')
    # ### end Alembic commands ###
