"""add joined_at column to users

Revision ID: 904586c6c715
Revises: 774a71079814
Create Date: 2022-02-20 15:21:01.507322

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904586c6c715'
down_revision = '774a71079814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joined_at')
    # ### end Alembic commands ###
